version: '3.3'
services:
  redomainer:
    container_name: redomainer
    build: ./container
    volumes: 
    - ./config/:/storage/config/:ro
    - ./logs/:/var/log/nginx/
    - ./certs/:/etc/letsencrypt/
    #- ./nginx/:/etc/nginx/ # TEST
    ports:
      - "80:80"
      - "443:443"